### PR TITLE
XS-2875: Update DQC with global master.

### PR DESCRIPTION
**Pull request by chrislococo-wf**
##### Pull request for: [XS-2875](https://jira.webfilings.com/browse/XS-2875)

[XS-2875](https://jira.webfilings.com/browse/XS-2875) - Update Workiva/DQC with the global upstream
#### Changes:
- Merged master from upstream. Only one conflict, which was not really a conflict but git not resolving correctly.

Please review: @jasonleinbach-wf @mindeerickson-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf

### CODE REVIEW

**Comment by andrewperkins-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1 for merge

**Comment by chrislococo-wf** [comment]
```
(dqc)  chrislococo [dqc] (XS-2875) $ ./dev-tests.sh
Running: nosetests
Verbosity: 2

consortium_rules on: refs/heads/XS-2875
consortium_rules at: 6d64d5279485fbb143b270996cf700406cfd6c37

test_axis_qnames (tests.unit_tests.util.test_facts.TestAxisQnames) ... ok
test_axis_qnames_no_axis (tests.unit_tests.util.test_facts.TestAxisQnames) ... ok
test_get_facts_dei (tests.unit_tests.util.test_facts.TestDei) ... ok
test_get_facts_with_type (tests.unit_tests.util.test_facts.TestDei) ... ok
test_lookup_dei (tests.unit_tests.util.test_facts.TestDei) ... ok
Tests to make sure that a Fact with a None type context is not valid ... ok
Tests to make sure that a None type fact is not valid ... ok
Tests to make sure that a Fact.context with a None type segDimValue is not valid ... ok
Tests to make sure that a valid fact still works ... ok
test_filter_duplicate_facts_None_contextID (tests.unit_tests.util.test_facts.TestFilterDuplicateFacts) ... ok
test_filter_duplicate_facts_duplicate_contextID_unitID (tests.unit_tests.util.test_facts.TestFilterDuplicateFacts) ... ok
test_ignore_units (tests.unit_tests.util.test_facts.TestFilterDuplicateFacts) ... ok
test_isNil_filtering (tests.unit_tests.util.test_facts.TestFilterDuplicateFacts) ... ok
test_xValid_filtering (tests.unit_tests.util.test_facts.TestFilterDuplicateFacts) ... ok
test_lookup_gaap (tests.unit_tests.util.test_facts.TestGaap) ... ok
test_member_qnames (tests.unit_tests.util.test_facts.TestMemberQnames) ... ok
test_first_ignored_unit (tests.unit_tests.util.test_facts.TestPrepareFactsForCalculation) ... ok
test_ignore_units (tests.unit_tests.util.test_facts.TestPrepareFactsForCalculation) ... ok
test_ignore_units_clean (tests.unit_tests.util.test_facts.TestPrepareFactsForCalculation) ... ok
test_ignore_units_single_item (tests.unit_tests.util.test_facts.TestPrepareFactsForCalculation) ... ok
test_prepare_facts_for_calculation_happy_path (tests.unit_tests.util.test_facts.TestPrepareFactsForCalculation) ... ok
test_prepare_facts_for_calculation_mixed_bag (tests.unit_tests.util.test_facts.TestPrepareFactsForCalculation) ... ok
test_scale_values_all_inf (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_all_missing_decimals (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_all_same (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_invalid_values (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_mix (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_negatives (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_positives (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_some_inf (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_scale_values_some_missing_decimals (tests.unit_tests.util.test_facts.TestScaleValues) ... ok
test_bv_None_context (tests.unit_tests.test_dqc_us_0004.TestAssetsEqLiabilityEquity) ... ok
test_bv_errors (tests.unit_tests.test_dqc_us_0004.TestAssetsEqLiabilityEquity) ... ok
test_bv_no_errors_duration (tests.unit_tests.test_dqc_us_0004.TestAssetsEqLiabilityEquity) ... ok
Make sure that the scale value is valid if it is infinity ... ok
Make sure that the scale value is valid when it is zero ... ok
Make sure that the scale value is not valid if it is Not a Number ... ok
Make sure that the scale value is valid if it is negative infinity ... ok
Make sure that the scale value is not valid if is not None ... ok
test_values_unequal_equal_values (tests.unit_tests.test_dqc_us_0004.TestAssetsEqLiabilityEquity) ... ok
test_values_unequal_unequal_but_still_equal_values (tests.unit_tests.test_dqc_us_0004.TestAssetsEqLiabilityEquity) ... ok
test_values_unequal_very_unequal_values (tests.unit_tests.test_dqc_us_0004.TestAssetsEqLiabilityEquity) ... ok
test_axis_exists_multi_axis (tests.unit_tests.test_dqc_us_0005.TestContextChecks) ... ok
test_dei_regex (tests.unit_tests.test_dqc_us_0005.TestContextChecks) ... ok
test_get_end_of_period_no_concept (tests.unit_tests.test_dqc_us_0005.TestContextChecks) ... ok
test_dei_regex (tests.unit_tests.test_dqc_us_0005.TestDeiChecks) ... ok
test_lea_facts_and_update (tests.unit_tests.test_dqc_us_0006.TestContextDates) ... ok
test_empty_compare (tests.unit_tests.test_dqc_us_0009.TestCompareFacts) ... ok
test_extant_compare (tests.unit_tests.test_dqc_us_0009.TestCompareFacts) ... ok
test_blacklist (tests.unit_tests.test_dqc_us_0015.TestBuildDict) ... ok
Verifies the actual exclusion rule config can be parsed with no ... ok
test_contains (tests.unit_tests.test_dqc_us_0015.TestDQC0015) ... ok
test_contains_insensitive (tests.unit_tests.test_dqc_us_0015.TestDQC0015) ... ok
test_equals (tests.unit_tests.test_dqc_us_0015.TestDQC0015) ... ok
test_parse_row (tests.unit_tests.test_dqc_us_0015.TestDQC0015) ... ok
test_a_warn (tests.unit_tests.test_dqc_us_0033_0036.TestDocPerEndDateChk) ... ok
test_a_warn_and_error (tests.unit_tests.test_dqc_us_0033_0036.TestDocPerEndDateChk) ... ok
test_an_error (tests.unit_tests.test_dqc_us_0033_0036.TestDocPerEndDateChk) ... ok
test_setup_facts (tests.unit_tests.test_dqc_us_0033_0036.TestDocPerEndDateChk) ... ok
test_length_one_dped (tests.unit_tests.test_dqc_us_0033_0036.TestGetDefaultDped) ... ok
test_multi_dped (tests.unit_tests.test_dqc_us_0033_0036.TestGetDefaultDped) ... ok
test_no_dped (tests.unit_tests.test_dqc_us_0033_0036.TestGetDefaultDped) ... ok
test_run_checks (tests.unit_tests.test_init.TestInitFunctions) ... ok

----------------------------------------------------------------------
Ran 63 tests in 1.482s

OK
```

**Comment by jasonleinbach-wf** [comment]
+10 - ran tests.  Verified.

**Pull request merged**
